load("@rules_cc//cc:defs.bzl", "cc_library")
cc_library(
    name = "cbdLibInclude",
    hdrs = ["cboardConst.h", "cboardTypeDef.h", "external.h", "stateIdDef.h"],
    visibility = ["//visibility:public"],
)