load("@rules_cc//cc:defs.bzl", "cc_library")
cc_library(
    name = "cboardcore",
    srcs = ["cboard.cxx"],
    hdrs = ["cboard.h", "cboardTypeDef.h", "stateIdDef.h", "external.h", "cboardConst.h"],
    visibility = ["//visibility:public"],
)