include: 
  - local: 'infra/container/gitlab-container.yml'
  - project: 'riscv/dv/gitlab-definitions'
    ref: main
    file: 'common-definitions.yml'

stages:
    - submodule_update
    - build

smoke:
    stage: build
    extends:
        - .bzsim-template
        - .smoke-rules-all-branches-template
    script:
        - python3 infra/git_getter.py
        - infra/bazel-wrap --output_base=. test //tests/...
    timeout: 1h

submodule_update:
    stage: submodule_update
    extends:
        - .submodule-update-template

infra_update:
    stage: submodule_update
    extends:
        - .infra-update-template

container_update:
    stage: submodule_update
    extends:
        - .container-update-template
