include: 
  - local: 'infra/container/gitlab-container.yml'
  - project: 'riscv/dv/gitlab-definitions'
    ref: main
    file: 'common-definitions.yml'

stages:
    - build

smoke:
    stage: build
    extends:
        - .bzsim-template
        - .smoke-rules-all-branches-template
    script:
        - python3 infra/git_getter.py
        - infra/bazel-wrap --output_base=. test //tests/...
    timeout: 1h
