#! /usr/bin/env bash

set -e
set -o pipefail

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
CONTAINER_DIR=$SCRIPT_DIR/podman-scripts

if $CONTAINER_DIR/cannot-run-container ; then
    exec $SCRIPT_DIR/gen_rtl_top.py "$@"
fi

PODMAN_RUN_OPTS="-v /tools_risc:/tools_risc" exec $CONTAINER_DIR/container-run-tt python3 $SCRIPT_DIR/gen_rtl_top.py "$@"
