#!/opt/miniconda3/bin/python3
import pandas as pd
import re
import os
import sys
import math
import argparse
import subprocess
import fileinput
import json
ROOTDIR = subprocess.check_output(["git", "rev-parse", "--show-toplevel"], universal_newlines = True).rstrip()
debug=0

## ******************************************************
## USAGE:
##    gen_rtl_top.py [-h] -cfg CFG [-hier HIER] 
## 
## Generate Top level RTL Verilog files based on Cluster configuration.
## 
## optional arguments:
##   -h, --help            show this help message and exit
##   -cfg CFG, --cfg CFG   Cluster configuration to build. eg: AS_SC_2Core (File = .json)
##   -hier HIER, --hier HIER
##                         Hier to run on: cl(Cluster), l2, as, fe, ls (Default is Core=AS)
## ******************************************************

class Inst():
  #Construct routine
  def __init__(self,args):
    print("Class: inst", "__name__ =", repr(__name__), "method = __init__") if debug else 0
    self.args = args
    self.cfg_name = args.cfg
    self.json_file_name = ROOTDIR+"/cfg/"+self.cfg_name+".json"
    self.json_data = ""
    self.gen_rtl_path = ROOTDIR+"/rtl/gen_files/"
    self.rtl_top_file_name = self.gen_rtl_path+self.cfg_name+"_top.sv"
    self.rtl_top_file = ""
    self.rtl_file_name = self.gen_rtl_path+self.cfg_name+".sv"
    self.header_txt = """/*************************************************************************
 * ### AUTOGENERATED FILE -- DO NOT EDIT HERE ###
 * >>> Use a config JSON file  to generate using infra/gen_rtl_top -cfg <json file><<<
 *************************************************************************
 *
 * Tenstorrent CONFIDENTIAL
 *__________________
 *
 *  Tenstorrent Inc.
 *  All Rights Reserved.
 *
 * NOTICE:  All information contained herein is, and remains
 * the property of Tenstorrent Inc.  The intellectual
 * and technical concepts contained
 * herein are proprietary to Tenstorrent Inc.
 * and may be covered by U.S., Canadian and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Tenstorrent Inc.
 */

"""
    self.auto_include_txt = """  (/*AUTOARG*/);
  input                               clk;
  input                               reset_n;
  /*AUTOINPUT*/
  /*AUTOOUTPUT*/
  /*AUTOLOGIC*/

"""
    self.footer_txt = """// Local Variables:
// verilog-library-directories:(".")
// verilog-library-extensions:(".sv" ".h" ".v")
// verilog-typedef-regexp: "_[eus]$"
// End:

"""

  def open_files(self):
    print("Class: Inst", "__name__ =", repr(__name__), "method = __open_files__") if debug else 0

    ## RTL TOP FILE
    self.rtl_top_file = open(self.rtl_top_file_name, "w")

  def read_cfg(self):
    print("Class: Inst", "__name__ =", repr(__name__), "method = __read_cfg__") if debug else 0
    print(" Reading in Configuration params JSON file")

    try:
      with open(self.json_file_name) as config_json:
        self.json_data = json.load(config_json)
        # print(data["Name"])
        # print(data["Config"])
        # print(data["Packages"])
        # print(data["Blocks"])

              ## print("df.k = ",self.df['Config'].loc[self.df['Config']['NAME'] == k]['Main'])
              ## try:
              ##   self.df['Config'].loc[self.df['Config']['NAME'] == k,'Main'] = v
              ## except:
              ##   print("WARNING: Did not find override param specified - %s = %s. Ignoring" %(k,v))
              ##   pass
    except:
      print("Error loading config params file %s Exiting" %(self.json_file_name))
      exit()

  def gen_toplevel(self):
    print("Class: Inst", "__name__ =", repr(__name__), "method = __gen_toplevel__") if debug else 0
    print(" Generating Top level files")
    #print("DEBUG>> %s" %(self.pkg_file))
    print_str =  (self.header_txt)
    print_str += ("module %s\n" %(self.json_data["Name"]))
    for o in self.json_data["Packages"]:
      for k,v in o.items():
        print(k,v)
        print_str += ("  import %s::*;\n" %(k))
    print_str +=  (self.auto_include_txt)
    for o in self.json_data["Blocks"]:
      for k,v in o.items():
        module_name = k
        for o1 in v:
          print_str += ("%s #(/*AUTOINSTPARAM*/) %s (/*AUTOINST*/);\n" %(module_name,o1["name"]))
          #for k1,v1 in o1.items():
    print_str += ("\nendmodule\n")
    print_str += (self.footer_txt)
    print(print_str, file=self.rtl_top_file)

  def auto_verilog(self):
    print("Class: Inst", "__name__ =", repr(__name__), "method = __auto_verilog__") if debug else 0
    print(" Generating Final Verilog")
    #print([ROOTDIR +"/infra/verilog-auto-gen.sh", self.top_files['src'], self.top_files['dest']])
    #print([os.path.join(os.path.dirname(os.path.realpath(__file__)), "verilog-auto-gen.sh"), self.top_files['src'], self.top_files['dest']])
    print(ROOTDIR+"/infra/verilog-auto-gen.sh", self.rtl_top_file_name, self.rtl_file_name)
    subprocess.run([ROOTDIR+"/infra/verilog-auto-gen.sh", self.rtl_top_file_name, self.rtl_file_name])

  def close_files(self):
    print("Class: Inst", "__name__ =", repr(__name__), "method = __close_files__") if debug else 0
    # self.json_file.close()
    self.rtl_top_file.close()

if __name__ == "__main__":
  parser = argparse.ArgumentParser(description='Generate Top level RTL Verilog files based on Cluster configuration')
  parser.add_argument("-cfg", "--cfg", type=str, required=True, help="Cluster configuration to build. eg: AS_SC_2Core (File = .json)")
  parser.add_argument("-hier", "--hier", type=str, required=False, help="Hier to run on: cl(Cluster), l2, as, fe, ls (Default is Core=AS)")
  #parser.add_argument("-notop", "--notop", action="store_true", default=True, help="TEMP: Dont generate top level files")
  if len(sys.argv)==1:
    parser.print_help()
    # parser.print_usage() # for just the usage line
    parser.exit()
  args = parser.parse_args()
  #print(args.accumulate(args.integers))

  newInst = Inst(args)
  newInst.open_files()

  newInst.read_cfg()
  print("\tJSON file read %s" %(newInst.json_file_name))

  newInst.gen_toplevel()
  print("\tTop level template file written to %s" %(newInst.rtl_top_file_name))

  newInst.close_files()

  newInst.auto_verilog()
  print("\tTop level RTL file written to %s" %(newInst.rtl_file_name))